<a href="https://colab.research.google.com/github/dylanRPS15/challlenge3/blob/main/Ejercicio_numpy_challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Challenge

Create a NumPy ndarray object by using this list of numbers [7,8,4,5,1,2].


In [ ]:
import numpy as np
arr = np.array([7,8,4,5,1,2])
print(arr)


[7 8 4 5 1 2]


Using slicing print the elements from index 3 to the end of the array.



In [ ]:
print(arr[3:])

[5 1 2]


Using slicing print all the elements except the last one.



In [ ]:
print(arr[:-1])

[7 8 4 5 1]


Using slicing print the elements from index 1 to index 4 of the array.



In [ ]:
print(arr[1:5])

[8 4 5 1]


Reshape the array into a 3 rows and 2 cols (3,2).



In [ ]:

newarr = arr.reshape(3,2)
print(newarr)
print(arr)

[[7 8]
 [4 5]
 [1 2]]
[7 8 4 5 1 2]


Print all the array elements one by one (iterating).



In [ ]:
for x in arr:
  print(x)

7
8
4
5
1
2


Create a new NumPy ndarray object by using this list of numbers [0,6,9].



In [ ]:
ndarray=([0,6,9])
print(ndarray)

[0, 6, 9]


Join the two arrays.



In [ ]:
arr1 = np.concatenate((arr, ndarray))
print(arr1)

[7 8 4 5 1 2 0 6 9]


Using filtering print only the odd numbers of the joined array.



In [ ]:
odd_numbers=[num for num in arr1 if num%2 !=0]
for odd_num in odd_numbers:
  print (odd_num)

7
5
1
9


Sort the joined array elements.



In [ ]:
arr1.sort()
print(arr1)

[0 1 2 4 5 6 7 8 9]



Store in an array the names of the months.



In [ ]:
months= ["January", "February", "March", "April", "May", "June", "July", "August","September", "October", "November", "December" ]
for month in months:
  print(month)

January
February
March
April
May
June
July
August
September
October
November
December


Split the months array in 4 periods of 3 elements each one.



In [ ]:
newmonths= np.array_split(months,4)
print(newmonths)
print(newmonths[0])

[array(['January', 'February', 'March'], dtype='<U9'), array(['April', 'May', 'June'], dtype='<U9'), array(['July', 'August', 'September'], dtype='<U9'), array(['October', 'November', 'December'], dtype='<U9')]
['January' 'February' 'March']


Create an array with genre information ['F','M','F','F','M','F'].



In [ ]:
genrei=(['F','M','F','F','M','F'])
print(genrei)

['F', 'M', 'F', 'F', 'M', 'F']


Find the indexes where the value is F.



In [ ]:
indexes = np.where(genrei == 'F')[0]
print(indexes)

[]


Store in an array the age information [18,20,19,23,19,20].



In [ ]:
age = ([18,20,19,23,19,20])
print(age)

[18, 20, 19, 23, 19, 20]


Create a filter array with values < 20.



In [ ]:

import numpy as np

age = np.array([18,20,19,23,19,20])

# Create an empty list
filter_age = []
for element in age:

  if element<20 :
    filter_age.append(True)
  else:
    filter_age.append(False)

newage = age[filter_age]

print(filter_age)
print(newage)

[True, False, True, False, True, False]
[18 19 19]


Change the 3 index element with a value of 22



In [ ]:
age[3]=22
print(age)

[18 20 19 22 19 20]


Print the 4 index element.

In [ ]:
print(age[4])

19
